### PR TITLE
Update Lithuanian.java

### PR DESCRIPTION
**Pull request by SlowLogicBoy**
Removed some redundant words.
Removed/Changed some words, because there are some words we don't used on a daily basis.
Changed some cringy text.
Made text less formal.
Fixed spelling

### CODE REVIEW

**Comment by MrMorkat** [comment]
Is there a way to say it without using gender specific words? How did the previous translation work around that issue?

**Comment by omkelderman** [comment]
@Tillerino will have to handle this, cuz the travis issue its still the same as last translation

**Comment by SlowLogicBoy** [comment]
> Is there a way to say it without using gender specific words?

I just changed them to completely different sentences, so they won't need gender specific words.
Also changed greeting to generic one.
>How did the previous translation work around that issue?

It was male specific.

**Comment by omkelderman** [comment]
from a structural point of view (aka some places need a specific space etc) looks all gud to me. Its now up to tillerino to give travis a bitch slap

**Comment by SlowLogicBoy** [comment]
Ping Pong :)

**Comment by omkelderman** [comment]
@Tillerino ding dong (its almost christmas isnt it xd)

**Pull request merged**
