### PR TITLE
Translate Chinese-Traditional.java

### PR DESCRIPTION
**Pull request by tomokarin**

### CODE REVIEW

**Comment by omkelderman** [comment]
just to confirm a thought I had, you did this thing by following the "Easy Way" on this page: https://github.com/Tillerino/Tillerinobot/wiki/Translating, right?

In case the answer is yes (which I think by the looks of it is probably the case) that guide is flawed.

**Comment by Tillerino** [comment]
@omkelderman the simple way is not intended to produce a proper pull-request, but it's fine.

@tomokarin what string should I use as a name for the language? `!set lang 官話` or `!set lang 官话` or something else?

**Comment by tomokarin** [comment]
@omkelderman Yes , i follow the "Easy Way" to do this.
@Tillerino Please use !set lang 繁體中文 for this language, thanks.

**Comment by omkelderman** [comment]
@Tillerino oh well, if its not suppose to produce proper pull-requests its fine i guess, but it's also more work for you :P

**Pull request closed without merging**
