### PR TITLE
Turkish.java

### PR DESCRIPTION
**Pull request by Lucri**

### CODE REVIEW

**Comment by Tillerino** [comment]
Should I call the language "Türkçe"?

**Comment by Lucri** [comment]
Yes,  it's türkçe,  is there any problem? 

Date: Sun, 8 Feb 2015 12:08:59 -0800

**Comment by Tillerino** [comment]
No, but I thought I'd rather ask. Did you see my comment on the `optionalCommentOnLanguage` message?

**Comment by Lucri** [comment]
If you are talking about this: " Sorry, this was not in the guide yet:The optionalCommentOnLanguage message is a special one. The bot sends it after you picked this language. Translating the English message makes no sense. Most translations use "YOUROSUNAME helped me learn YOURLANGUAGE" here."

Yes. I didn't know i'd translate the language name i thought you wouldn't understand it. The turkish version of this sentence is " Lucri bana Türkçe'yi öðrenmeme yardým etti."Date: Mon, 9 Feb 2015 08:10:38 -0800

**Comment by Tillerino** [comment]
Should be live now.

**Pull request closed without merging**
