### PR TITLE
Translate LIETUVIU.java

### PR DESCRIPTION
**Pull request by peraz**
Please contact www.reddit.com/u/peraz if I missed something or any questions regarding my translation :)

Also, if you will put it in the next update, the correct word for my language is "Lietuvių" :)

### CODE REVIEW

**Comment by Tillerino** [comment]
Is `!set lang Lietuvių` fine?

**Comment by peraz** [comment]
Yes it is.

**Comment by Tillerino** [comment]
What about this? https://github.com/peraz/Tillerinobot/commit/ac6e4e9382215b3c5daba609aed1b155b0d33398#commitcomment-9751753

**Comment by peraz** [comment]
1. I think the last translation is the same, I just deleted the comment in the end.
2. What do you mean by need more info? What is missing?

**Comment by Tillerino** [comment]
Your translation of `optionalCommentOnLanguage`; if you plain translate it, it doesn't make sense. The guide says the following on this:

The optionalCommentOnLanguage message is a special one. The bot sends it after you picked this language. Translating the English message makes no sense. Most translations use "YOUROSUNAME helped me learn YOURLANGUAGE" here.

**Comment by peraz** [comment]
Alrigt, I updated it.

The reason why this command causes so many problems is because your explanation sounds really programmish, like taking YOUROSUNAME and YOURLANGUAGE for commands, general Osu names, not the specific translator's name. It's confusing. Add a comment near that command and change the explanation to something like this:
"This is the credit line for you, the translator. You have to write your own Osu nickname and your language name, once the person will set your language ingame, Tillerino will reply with the credit line for you, write it like this in the language you are translating to: YOURNAME helped me learn YOURLANGUAGE"

Well, that was an example, but every translator is failing at this part and it's not like we are all just straight up retarded, it's just rather confusing.

**Comment by peraz** [comment]
Small fix: changed one word because my last translation wasn't appropriate for the situation.

**Pull request closed without merging**
