### PR TITLE
Update Portuguese.java

### PR DESCRIPTION
**Pull request by RagingAlien**
First translation. Will edit and spellcheck later. Any help appreciated.

Commands also need changing to portuguese. For now all commands are in English.

### CODE REVIEW

**Comment by RagingAlien** [comment]
Both fixes done. If I'm going to change the commands it'd also be necessary to translate the wiki, though, otherwise !help would just send them to a page listing the commands in english.

**Comment by Tillerino** [comment]
I manually merged this. Can you check if everything is working as expected?

**Comment by RagingAlien** [comment]
I'm busy with something else at the moment, but when I'm able I'll check it.

**Comment by RagingAlien** [comment]
Seems to work perfectly. Just going to take a while to make sure everything is correct. I commit quite a few spelling mistakes, and there's probably some I haven't fixed yet.

**Comment by Tillerino** [comment]
Suggestions by https://osu.ppy.sh/u/wow

Line 22: Aff... Parece que o Tillerino de verdade ferrou (...) (ferrou means screwed up, so i think that is not the best way to translate it) Should be (imo): Aff... Parece que o Tillerino de verdade bagunçou (...)

Line 29: O que é isso? Só estou conseguindo bobagens do servidor do osu. Should be: O que é isso? Só estou recebendo bobagens do servidor do osu.

Line 117: Desculpe, mas tinah (...) Should be: Desculpe, mas tinha (..)

Line 133: Olá! Sou o robô que matou o Tillerino e está usando a conta dele. Should be: Sou o robô que matou o Tillerino e estou usando a conta dele.

Line 161:Parece que este mana (...) Should be: Parece que este mapa (...)

**Comment by RagingAlien** [comment]
Okay, so I fixed that stuff, only needs to be merged again.

**Comment by Tillerino** [comment]
Oh, these changes are already live.

**Pull request closed without merging**
