### PR TITLE
Create Swissgerman.java

### PR DESCRIPTION
**Pull request by maurice-4**
Swissgerman translation from German

### CODE REVIEW

**Comment by omkelderman** [comment]
owo, looks gud!

One thing tho: about the "optionalCommentOnLanguage" message. I suppose you took the german translation as a base for this one, but if you look in the default language file there is this block: https://github.com/Tillerino/Tillerinobot/blob/9cca79339cc62e6b3377a39af46fee6b4e67158f/tillerinobot/src/main/java/tillerino/tillerinobot/lang/Default.java#L167-L195

Tldr: that message is not really a translation, but a message that shows after the end user switched language and usually translators put a message in there crediting themselfs. Now is isnt needed, so the current message works fine I suppose, but just wanted to make sure you're aware of this.

Then another question: what is the name of the language, in the language itself. For example to pick german as a translation you have to use the command `!set lang Deutsch`. What would that be for Swissgerman?

**Comment by maurice-4** [comment]
Thank you for pointing out the Language Message, i changed it.
Also regarding the name in Swissgerman its "Schwiizerdütsch".

**Comment by omkelderman** [comment]
awesome, looks good. I'll merge this as soon as I have time to do so 😃

**Comment by omkelderman** [comment]
@Tillerino travis is still broken, I think, afaik the translation should be fine now, can you look at it and merge it?

**Pull request merged**
