### PR TITLE
Added some missing Lithuanian translations.

### PR DESCRIPTION
**Pull request by SlowLogicBoy**

### CODE REVIEW

**Comment by omkelderman** [comment]
completing translations is always awesome, thanks!

Can you be more awesome by also translating the complete `apiTimeoutException`? If you look at the orignal in https://github.com/Tillerino/Tillerinobot/blob/master/tillerinobot/src/main/java/tillerino/tillerinobot/lang/Default.java (which you have done for these bits right?) then you can see on line 222-237 a bunch of "something to do" messages. If you could include those in the translation that would make it perfect :smile:

**Comment by SlowLogicBoy** [comment]
Just translated some of them that seemed appropriate and additionally added some of them. However not much that would be more relative in our country :/

**Comment by omkelderman** [comment]
well, sure I guess :stuck_out_tongue: looks good enough to me

And dont worry about the build-errors, I'll fix that ;)

**Comment by SlowLogicBoy** [comment]
Well, I don't have java environment setup, so I just play hit or miss with travis :D

**Comment by omkelderman** [comment]
well, if you wanna do it, iirc the only thing you're missing right now is the `rnd` object, look at the default class its somewhere on top

**Comment by SlowLogicBoy** [comment]
And I have a goal ^^

**Comment by omkelderman** [comment]
And I can just merge this with a press of a button in the github webinterface and I dont have to fire up my local dev stuff to do it, yay :smile:

**Comment by SlowLogicBoy** [comment]
^^, thanks for the merge. These translations bugged my so I translated them..
There are still some things that are bugging me like:
image

**Comment by omkelderman** [comment]
yeah, those are not translatable right now :disappointed:

**Comment by MrMorkat** [comment]
Unfortunately that cannot be changed at the moment

**Comment by omkelderman** [comment]
btw, hop on discord to claim your translators role if you want xd

**Pull request merged**
