### PR TITLE
Translate Japanese.java

### PR DESCRIPTION
**Pull request by Soukyuen**
It's not the most formal of the Japanese launguage, but it's mostly formal with a pinch of friendliness.

### CODE REVIEW

**Comment by Tillerino** [comment]
So what's the label of the language here? Is `!set lang 日本語` fine? I'm completely in the dark ^^

**Comment by Soukyuen** [comment]
Is this the right place to reply? Yes, that should be good.

**Comment by Tillerino** [comment]
Alrighty, I think I have everything I need.

**Comment by Tillerino** [comment]
Should be available now.

**Pull request closed without merging**
