### PR TITLE
Norwegian

### PR DESCRIPTION
**Pull request by Tillerino**

### CODE REVIEW

**Comment by Tillerino** [comment]
Is `!set lang Norsk` fine?

**Comment by Lepantoe** [comment]
Yeah, Norsk is fine

**Comment by Tillerino** [comment]
Please address the comments above

**Comment by Lepantoe** [comment]
damn, sorry about that, didnt read this until now, anyway, i dont know how to access the string again so ill just post the strings translation here: "Syntaxen for å sette et parameter er !set alternativ verdi. Prøv !help om du behøver flere veiledninger.";

**Comment by Lepantoe** [comment]
damn, sorry about that, didnt read this until now, anyway, i dont know how to access the string again so ill just post the strings translation here: "Syntaxen for å sette et parameter er !set alternativ verdi. Prøv !help om du behøver flere veiledninger.";

**Comment by Tillerino** [comment]
about `optionalCommentOnLanguage`

```
TRANSLATION NOTE: This line is sent to the user right after they have 
chosen this Language implementation. The English version refers to    
itself as the default version ("just the way I am"), so translating   
the English message doesn't make any sense.                           
                                                                      
Instead, we've been using the line                                    
"*Translator* helped me learn *Language*." in translations. Replace   
*Translator* with your osu name and *Language* with the name of the   
language that you are translating to, and translate the line into the 
new language. This serves two purposes: It shows that the language    
was changed and gives credit to the translator.                       
                                                                      
You don't need to use the line above, and you don't have have to give 
yourself credit, but you should show that the language has changed.   
For example, in the German translation, I just used the line          
"Nichts leichter als das!", which translates literally to             
"Nothing easier than that!", which refers to German being my first    
language.                                                             
                                                                      
Tillerino                                                             
                                                                      
P.S. you can put a link to your profile into the line like this:      
[https://osu.ppy.sh/u/2070907 Tillerino]                              
```

**Pull request closed without merging**
