### PR TITLE
Czech.java

### PR DESCRIPTION
**Pull request by Polarni**
Czech translation.

### CODE REVIEW

**Comment by Tillerino** [comment]
What should I use as the name of the language? čeština or just český? I need it for the command, so `!set lang český`

**Comment by Polarni** [comment]
český is wrong, please change to čeština.

**Comment by Tillerino** [comment]
Small detail, can use Čeština with an uppercase letter?

**Comment by Polarni** [comment]
yea my fail, thx ^^

**Comment by Tillerino** [comment]
Ok, I manually merged this. Will be included in next update.

**Comment by Tillerino** [comment]
live

**Pull request closed without merging**
