### PR TITLE
Recommend Options new

### PR DESCRIPTION
**Pull request by EnderAPOX**
Same commands improved code.

### CODE REVIEW

**Comment by EnderAPOX** [comment]
Only the install commands failed. My code should be fine.

**Comment by omkelderman** [comment]
> My code should be fine.

Well... nope, it doesnt even compile, as the Travis build already tells

**Comment by EnderAPOX** [comment]
http://i.imgur.com/cVojgvf.jpg

**Comment by omkelderman** [comment]
http://omk.pics/1/tQaxo.png

**Comment by EnderAPOX** [comment]
If that's so it's probs a variable causing tge problem. Ill have a look into it tomorrow.

**Comment by Cleverdawn** [comment]
A value to specify the pp min we get at 95% would be very handy : !r dt 150 would show you a map that give at least 150 pp at 95%

**Comment by omkelderman** [comment]
@Cleverdawn You are welcome to leave your suggestion in a new issue, lets leave this conversation on-topic ^^

**Comment by Cleverdawn** [comment]
Oh okay : 3 Sorry ^^

**Comment by Tillerino** [comment]
Since nothing has happened here, I'll close this.

**Pull request closed without merging**
