### PR TITLE
Portuguese(PT-PT).java

### PR DESCRIPTION
**Pull request by ThatGuy986**
Portuguese(PT-PT) translation by [HDHR]

### CODE REVIEW

**Comment by Tillerino** [comment]
Disregard #39 I guess?

**Comment by ThatGuy986** [comment]
Yes

2015-02-18 19:07 GMT+00:00 Tillerino <notifications@github.com>:

**Comment by Tillerino** [comment]
There's a Brazilian-Portuguese translation, which is called Português, which I didn't know was Brazilian-Portuguese, because how  would I know. It's no problem to change, but I'll need some help properly naming these.

I'll just make a suggestion and you tell me why it's dumb.

Português_Brasil and
Português_Internacional

**Comment by ThatGuy986** [comment]
Português_BR
Português_PT

or

Português(PT-BR)
Português(PT-PT)

**Comment by Tillerino** [comment]
I ended up using `Português_BR` and `Português_PT`.

**Pull request closed without merging**
