### PR TITLE
Fixed some grammar and interpunction errors in Polish translation

### PR DESCRIPTION
**Pull request by xParadoxical69**
I don't know what lang-update branch is, so i made edits in master branch

### CODE REVIEW

**Comment by qewc** [comment]
Pretty sure that branch is for language updates

**Comment by xParadoxical69** [comment]
yeah, i know it, but it's missing many commits, it looks like it's old, so i didn't touch it

**Comment by qewc** [comment]
If it's only for translation what do you expect

**Comment by omkelderman** [comment]
The lang update branch has been used for some language related code changes at some point in the past. You can pretty much ignore it and I should probably just remove it, it serves no purpose anymore.

As for this PR, I don't have time right now to look at it, I'll most likely be able to do that tomorrow. Feel free to remind me if I forget

**Pull request merged**
