### PR TITLE
Languages

### PR DESCRIPTION
**Pull request by EvanvanUrk**
Added Dutch language implementation

### CODE REVIEW

**Comment by omkelderman** [comment]
hey, i was working on that xd
(to be fair, i started once long time ago and never finished it xd)

Anyhow, looks good! Way better than the start i have laying around somewhere

**Comment by Tillerino** [comment]
Oh man, sorry @omkelderman. I completely forgot.

@EvanvanUrk can you squash the commits please?

**Comment by EvanvanUrk** [comment]
Should have squashed them, @Tillerino. Not too sure since I haven't used the squash command before.

Sorry for stealing your spotlight @omkelderman ;o;

**Comment by omkelderman** [comment]
dont worry guys, i had waaay to little time to do this anyway. And as said, this one is better anyway

**Comment by notadecent** [comment]
I would like to fix some more grammatical errors but am not allowed to push to the branch.

**Comment by EvanvanUrk** [comment]
I added you as a collaborator so you can make your changes.

**Pull request merged**
