### PR TITLE
Fixed Hungarian translation

### PR DESCRIPTION
**Pull request by moriczgergo**
Note: should I remove the last commit?

### CODE REVIEW

**Comment by MrMorkat** [comment]
The last commit is fine in my opinion, as the original author still gets credit in the wiki :P But idk, @OMKelderman thoughts?

**Comment by moriczgergo** [comment]
I thunk it's fine because he literally deleted his GitHub

**Comment by omkelderman** [comment]
github might be deleted, looks like osu account is still there. So lets keep that one in the credits.
Also preferably link osu-accounts with user-id in the url instead of username, so it survives a possible namechange

**Comment by moriczgergo** [comment]
Alright, I've added him back. But he haven't played in a long time, and has his PP cleared out, just sayin'.

**Comment by omkelderman** [comment]
so? someone did work, so someone deserves credit

Either way, looks good to me now :ok_hand:

**Pull request merged**
