### PR TITLE
Languages

### PR DESCRIPTION
**Pull request by Shavitush**
I'm not sure how do I add my edited file there but here it is https://a.pomf.se/lbfcfi.java (Hebrew.java)

### CODE REVIEW

**Comment by Tillerino** [comment]
Ok, whoa. Different character set. A couple of things:

You left the English messages in a couple of places, could you remove them, please?

Also what's "Hebrew" in Hebrew? I need to know how to name the language.

And could you make the `optionalCommentOnLanguage` message the translation of

    shavitush helped me learn Hebrew.

**Comment by Shavitush** [comment]
Whoops my bad

Fixed https://a.pomf.se/gutpvh.java

**Comment by Tillerino** [comment]
Ok, wow. I can't edit that file at all. I need help. Can you come over here for a second? https://gitter.im/Tillerino/Tillerinobot

**Comment by Tillerino** [comment]
Lol, this was automatically closed because the pull request was for something different ^^

Anyway, it's live now. How is everything looking?

**Comment by Shavitush** [comment]
It works fine, good to have it now

**Pull request merged**
