### PR TITLE
Live discord icon and link

### PR DESCRIPTION
**Pull request by ChemiHatake**
probably looks better this way

### CODE REVIEW

**Comment by omkelderman** [comment]
TIL you can put html in md files :open_mouth: 

I much say, i kinda like it, but somehow I feel some text with "click here to join" probably cant hurt :stuck_out_tongue: 

Also, github caches the images through its camo-system, so the "online user count" will presumably always be "old"/incorrect

**Comment by ChemiHatake** [comment]
<p align="center">
  <a href="https://discordapp.com/invite/0ww19XGd9XsiJ4LI">
    Logo
  </a>
</p>

**Comment by ChemiHatake** [comment]
there's a chat now text in this one

**Comment by omkelderman** [comment]
from the possible banner-style options, I think I like this one the most:
join discord

cuz it has an explicit "join" button ^^ you can never be too clear to ppl xd

**Comment by ChemiHatake** [comment]
isn't it too big? @omkelderman

**Comment by omkelderman** [comment]
nah, there is pretty much nothing on that readme page anyway xd (unless @Tillerino has plans I dont know of), I kinda like the in-your-face-part of it :stuck_out_tongue:

**Pull request merged**
